### ISSUE TITLE
Readme has a 404

### ISSUE THREAD

**Issue by ryanlitalien** [skx/github-action-tester#1]
Hey! Quick note, your README has a link to `https://github.com/skx/math-compiler/actions`, and that gives me a 404 (there's no "Actions" tab on that repo). Good luck!

**Comment by skx** [comment]
That's a frustrating one, for me the link is valid and correct.

I suspect that means that you've not been invited to the actions-beta..?

**Comment by ryanlitalien** [comment]
No worries. I have been invited sir! Here's a pic of your repo:
![image](https://user-images.githubusercontent.com/1479756/53423168-db6da700-39ae-11e9-8310-201077b35c31.png)

I think Actions are available to the maintainer (or collaborator) and aren't available to the public? Starting investigating into actions myself.

**Comment by skx** [comment]
You might be right about the visibility; I'll upload a screenshot in place of the link later this evening.

Thanks for the report :)

**Comment by ryanlitalien** [comment]
👍
