### ISSUE TITLE
`exit $?` in entrypoint.sh is misleading

### ISSUE THREAD

**Issue by yuantailing** [skx/github-action-tester#5]
https://github.com/skx/github-action-tester/blob/971caca9b050faa982bb5519d619852f75ec47bc/entrypoint.sh#L12-L16

`exit $?` in entrypoint.sh is useless since `set -e`.

If run-tests.sh fails, the bash quits and `exit $?` will not be executed.

**Comment by skx** [comment]
Thanks for the report.

You're correct, of course.
